### ISSUE TITLE
Windows/cross-platform support

### ISSUE THREAD

**Issue by neothematrix** [raymondbutcher/pretf#42]
hello!
first of all, thanks for the awesome module!
I know my reuqest is controversial, but...do you think it would be possible to make your module cross-platform? At the moment, I tried running it on windows, and I found 2 issues, one can probably be easily solved:

1) pretf cannot find the terraform executable:
`terraform_path = os.path.join(path, "terraform")`
on Windows, terraform exe will be named "terraform.exe" so the terraform_path should be different based on the OS, quickly modifying that to: 
`terraform_path = os.path.join(path, "terraform.exe")`
temporarily worked around the issue, but it lead me to the real issue:

2) os.fork() is not supported on Windows, I guess there could be other way to fork that are multi-platform, but my skills stop here.

I know that it would be possible to use linux sub-system on windows, but that's not my goal.

Feel free to just "close" this issue :-)

**Comment by raymondbutcher** [comment]
Hi,

Thank you. Don't worry, I do want this to work on Windows. I just haven't implemented this myself because I personally don't use Windows for development. Pull requests are welcome though.

There are many Windows + Terraform users at [Claranet](https://github.com/claranet) where I work so ideally I will get some buy-in to do this on company time, but I wouldn't hold my breath. I'd have to convince people in other teams to start using Pretf first.

Besides the issues you mentioned, the only other thing I can think of is the use of symlinks in `pretf.workflow.mirror_files()`. It's only for optional use in custom workflows, so it wouldn't be a blocker if it didn't work. I have read that symlinks (or junctions?) do work in Windows so it might be fine, who knows.
